dist: xenial

language: python

services:
  - postgresql

python:
  - 3.8

before_install:
  - python --version
  - pip install -U pip
  - pip install codecov

env:
  - DJANGO_VERSION=3.1.2

install:
  - pip install -r requirements.txt
  - pip install -q Django==3.1.2
  - python setup.py -q install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py collectstatic --noinput
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test

after_success:
  - codecov

before_deploy: echo 'ready?'

deploy:
  provider: heroku
  api_key:
    secure: TN76OxAIJQ3/S0rfw+yDRFQ75v2Y9wd6CuCRJcUpl6BYqaIAbLYI9h8tfcaF9QxCCY1h/9+WePwIzn0xfKAWb9dLNBztnvW9XAmmU2OzeR74PbS/lHOMDftRN7sPShAIVJyNESNh5W7As8Xqkf1NZLThrs4iUMMjnu7qxp/iWHFpvhaYZ3qya+q7GYB01aVl24NAORVg3uLN+2RC2hdnAOiTFo/ob2IEgsTwlIS3ITISBt3oJSbieeUq92qu0UdT2wwxySyEKuQ/SdXEXAUwP9H9cYV+yCwR9UQCi3gri2Jzztq1VehJevDzXnjG4qg76TQYqpCTsvWc403FrUYSsja8NGNHxOPVl7lwLdHC98LOjviSB1gic536HJS9ozlezh6JG7utEJRVq5yODuL+6w6QeWOx+fiUPhkEJ49zA/5C3QxVPHq+SsuEJE3xj4kHbZTPz7LrTJoRopej1N0is4xtBwLMXY6nZuSlJ0tGMXRjAJCK7YN7E/cyIdak5ZW/41Wrkg+jLWIg9auaqt057tbRsJC/GGcVaim8GaDT6W/IGXoSz51fSJSokJtMS5sngIEOSBKFwUKZsEIjLuIsBeuWm0xgoLDqqPa79qDau0dnhja/pxdAG44E5FnIu+pU31052Ty2EIaxrm3ojxmr+HCjnaQHk+cAU6RGJAVmLNs=
  app: dummy-register
  on:
    repo: faisaladisoe/House-of-great
